### ISSUE TITLE
Config doesn't use recommended MAC address range

### ISSUE THREAD

**Issue by desertmonkey** [CumulusNetworks/cldemo-config-mlag#1]
In the docs, we have the reserved MAC address range as being from 44:38:39:ff:00:00 to 44:38:39:ff:ff:ff. (https://docs.cumulusnetworks.com/display/DOCS/Multi-Chassis+Link+Aggregation+-+MLAG#Multi-ChassisLinkAggregation-MLAG-ReservedMACAddressRange)

However, clagd-sys-mac on farm08 has 44:39:39:FF:40:94 (44:39:39 instead of 44:38:39). 

Not a huge deal but it'd be nice to follow our recommendations.

**Comment by ericpulvino** [comment]
Looks like a typo... good catch.

**Comment by ollyg** [comment]
I believe this issue can be closed, now.
