### ISSUE TITLE
use VLAN-aware bridge

### ISSUE THREAD

**Issue by IPvSean** [CumulusNetworks/cldemo-config-mlag#5]
we need to switch to VLAN-aware bridge and show multiple SVIs

**Comment by ericpulvino** [comment]
There is an NCLU Config branch which contains the updated configs for Vlan Aware Bridge (VAB).

**Comment by ollyg** [comment]
OK thanks - I've created a small pull request for the minimum required for VLAN aware bridge (sorry I hadn't spotted the NCLU branch). However the NCLU branch seems to contain a _lot_ more changes with I've not looked at, so I'll let you decide which you want to merge to master :-). Happy for you to close my PR if you prefer the NCLU branch option!

**Comment by ericpulvino** [comment]
Thanks!
